version: '3.8'

services:
  evolutionapi:
    image: devfullcycle/evolution-api# Aquí le decimos que use el molde oficial de Evolution API.
    container_name: evolution_api # Le damos un nombre fácil de identificar.
    restart: unless-stopped # Le decimos que se reinicie solo si falla.

    ports:
      - "8080:8080" # Hacemos que la API sea accesible en el puerto 8080.

    environment:
      # --- Configuración del Servidor ---
      - PORT=8080
      # --- Clave de API Global para la instancia ---
      # Esta es la contraseña maestra para usar tu API. ¡Guárdala!
      - API_KEY=Hodify_es_mi_clave_secreta_12345
      
      # --- Configuración de la Base de Datos (usará un archivo local) ---
      - DATABASE_ENGINE=local-sqlite
      - DATABASE_CONNECTION_URI=./instances.db
      
      # --- Configuración para guardar los datos de WhatsApp ---
      - STORE_MESSAGES=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true

    volumes:
      # --- Aquí guardamos los datos para que no se borren ---
      # Crea una carpeta "evolution_data" para la base de datos.
      - ./evolution_data:/evolution/data
      # Crea una carpeta "instances" para guardar las conexiones de WhatsApp.
      - ./instances:/evolution/instances
