version: '3.7'

services:
  evolution:
    image: athenda/evolution-api:latest # La imagen oficial y correcta
    container_name: evolution_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DATABASE_ENABLED=true
      - DATABASE_ENGINE=mongodb
      - DATABASE_CONNECTION_URI=mongodb://mongo:27017
      - DATABASE_NAME=evolution_api
      - API_KEY=${API_KEY} # Lee la API Key desde Dokploy
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=${API_KEY}
    volumes:
      - ./evolution_instances:/evolution/instances
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./mongodb_data:/data/db
